Default: &defaults
  database: yaghnob-todo.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: yaghnob-todo_test.sqlite3
  <<: *defaults

Staging:
  database: yaghnob-todo_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: yaghnob-todo_production.sqlite3
  poolsize: 100
  <<: *defaults
